Key-value Persistent Storage Unit Task
csc-bdse-group-42/csc-bdse pull request #2
Opened 2018-02-28 18:53 UTC by StepaMalkevich

2018-03-02 17:26 UTC, alesavin commented
Не реализованы интеграционные тесты ноды с поднятием (и выключением) в контейнерах СУБД, ноды (KeyValueApiHttpClientTest2). Будете доделывать?

2018-03-03 09:55 UTC, istarion commented
@alesavin , да, будем доделывать. Не смотрели эти тесты т.к. они были зелёные.

2018-03-04 14:12 UTC, istarion commented
@alesavin , тесты добавлены.

2018-03-04 20:23 UTC, alesavin commented
При запуске KeyValueApiHttpClientTest

```
org.assertj.core.api.SoftAssertionError: 
The following assertion failed:
1) [size] 
Expected size:<1> but was:<2> in:
<[NodeInfo{name='node-0', status=UP}, NodeInfo{name='DEFAULT', status=UP}]>


	at org.assertj.core.api.SoftAssertions.assertAll(SoftAssertions.java:116)
	at ru.csc.bdse.kv.AbstractKeyValueApiTest.getClusterInfoValue(AbstractKeyValueApiTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

что в действительности правильно - структура NodeRepository излишняя, по сути более одной ноды в репозитории не может быть (в рамках одной jvm), ну и "DEFAULT" вроде как лишний. Предлагаю просто хранить статус  в приватном поле как в https://github.com/DB1L/csc-bdse/blob/master/bdse-kvnode/src/main/java/ru/csc/bdse/kv/RedisKeyValueApi.java .

Кажется доделка небольшая, давайте добьем?

2018-03-04 20:25 UTC, alesavin requested changes

2018-03-04 20:25 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/BerkleyKeyValueApi.java
> +        try (EntityCursor<KeyValueRecord> cursor = primaryIndex.entities()) {
кажется есть primaryIndex.keys() - лучше использовать его?

2018-03-04 20:25 UTC, alesavin commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/BerkleyKeyValueApi.java
> +        try (EntityCursor<KeyValueRecord> cursor = primaryIndex.entities()) {
почему бы не сразу primaryIndex.delete()?

2018-03-08 20:17 UTC, alesavin approved these changes
Принято без тестов, но балл невелик

2018-03-10 15:12 UTC, istarion commented
@alesavin , исправил все замечания.

2018-03-10 15:16 UTC, merged