Task2. Phone Book 1.0, 1.1
csc-bdse-group-42/csc-bdse pull request #3
Opened 2018-03-15 20:02 UTC by StepaMalkevich

2018-03-17 16:53 UTC, 747mmHg commented on bdse-app/src/main/java/ru/csc/bdse/app/v2/controller/BookControllerV2.java
> +                      @RequestParam("secondName") String nickName,
Неправильное имя параметра

2018-03-17 16:58 UTC, 747mmHg commented on bdse-app/src/main/java/ru/csc/bdse/app/v1/controller/BookControllerV1.java
> +    @RequestMapping(method = RequestMethod.PUT, value = "/add-person-v1")
Вообще, если делать API по REST, то правильнее было бы так:
update: `PUT /v1/person`
delete: `DELETE /v1/person`
get: `GET /v1/person`

Но это минор, можно не переделывать

2018-03-17 17:01 UTC, 747mmHg commented on bdse-app/src/main/java/ru/csc/bdse/app/v1/service/ServiceV1.java
> +        String secondName = record.getSecondName();
А если несколько человек имеют одинаковую фамилию? Кажется, что первичным ключом всё-таки является фамилия + имя

2018-03-17 17:02 UTC, 747mmHg commented on bdse-app/src/main/java/ru/csc/bdse/app/v1/service/ServiceV1.java
> +        RecordBookProtos.AddressBook.Builder addressBook = RecordBookProtos.AddressBook.newBuilder();
А зачем нужна обертка в виде `AddressBook`?

2018-03-17 17:05 UTC, 747mmHg commented on bdse-app/src/main/java/ru/csc/bdse/app/v2/service/ServiceV2.java
> +        for (String key : berkleyKeyValueApi.getKeys("")) {
Итерироваться по всем записям в сторадже — это супер неоптимально. Здесь ожидается что-то подобное способу, использованному в первой версии сервиса.

2018-03-17 17:30 UTC, 747mmHg commented
Коммитить сгенерированный код — это очень плохая идея. Мы не будем снижать за это оценку, но пожалуйста, никогда не делайте так в реальных проектах. Для кроссплатформенной компиляции proto файлов без необходимости устанавливать protoc можно использовать комбинацию Maven плагина `org.xolstice.maven.plugins:protobuf-maven-plugin` и Maven extension `kr.motd.maven:os-maven-plugin`
Конфигурация выглядит примерно так:
```
                <plugin>
                    <groupId>org.xolstice.maven.plugins</groupId>
                    <artifactId>protobuf-maven-plugin</artifactId>
                    <version>0.5.0</version>
                    <extensions>true</extensions>
                    <configuration>
                        <checkStaleness>true</checkStaleness>
                        <protocArtifact>
                            com.google.protobuf:protoc:3.4.0:exe:${os.detected.classifier}
                        </protocArtifact>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>compile</goal>
                                <goal>test-compile</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>

...

            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.5.0.Final</version>
            </extension>
```

2018-03-17 17:40 UTC, 747mmHg commented on bdse-integration-tests/src/test/java/ru/csc/bdse/app/PhoneBookNonFunctionalTest.java
>      @Test
В аннотацию `Test` можно в качестве параметра передать тип ожидаемого исключения и не писать вручную проверку того, что оно было выброшено.

2018-03-17 17:44 UTC, 747mmHg requested changes
Нужно как минимум починить удаление лишних записей по фамилии и избавиться от итерации по всем записям в `ServiceV2`

2018-03-19 07:53 UTC, 747mmHg commented on bdse-app/src/main/java/ru/csc/bdse/app/v1/service/ServiceV1.java
> +        String id = recordKey(record) + UUID.randomUUID().toString();
Непонятно, зачем нужен UUID — с одной стороны он позволяет хранить больше, чем одну запись с совпадающими именем/фамилией, с другой стороны удаление записи по имени/фамилии будет удалять их обе. Если мы считаем первичным ключом имя+фамилию, то можно упростить и вообще убрать UUID

2018-03-19 09:12 UTC, sinesight commented on bdse-app/src/main/java/ru/csc/bdse/app/v1/service/ServiceV1.java
> +        String secondName = record.getSecondName();
Fixed.

2018-03-19 09:14 UTC, sinesight commented on bdse-app/src/main/java/ru/csc/bdse/app/v1/service/ServiceV1.java
> +        RecordBookProtos.AddressBook.Builder addressBook = RecordBookProtos.AddressBook.newBuilder();
Действительно. Убрал.

2018-03-19 09:51 UTC, 747mmHg commented
Осталось решить проблему с интерацией по всем записям в базе.

2018-03-19 16:44 UTC, sinesight commented on bdse-app/src/main/java/ru/csc/bdse/app/v2/service/ServiceV2.java
> +        for (String key : berkleyKeyValueApi.getKeys("")) {
Исправлено (?)

2018-03-19 16:45 UTC, sinesight commented on bdse-app/src/main/java/ru/csc/bdse/app/v1/service/ServiceV1.java
> +        String id = recordKey(record) + UUID.randomUUID().toString();
Убрал.

2018-03-19 17:07 UTC, sinesight commented on bdse-integration-tests/src/test/java/ru/csc/bdse/app/PhoneBookNonFunctionalTest.java
>      @Test
Fixed.

2018-03-19 18:31 UTC, 747mmHg commented on README_TASK2.md
> +* Предполагается, что поле Фамилия не начинается с символа '@'.
Можно бы добавить проверку на уровне API, чтобы у пользователя не было возможности нарушить это правило

2018-03-19 18:34 UTC, 747mmHg commented on bdse-app/src/main/java/ru/csc/bdse/app/v1/service/ServiceV1.java
> +        return record.getSecondName() + record.getFirstName();
Совсем хорошо было бы вставлять какой-нибудь разделитель, чтобы исключить ситуации aab + bb = aa + bbb

2018-03-19 18:38 UTC, 747mmHg requested changes
Надо починить проблему с одинаковыми никнеймами, в остальном норм

2018-03-19 18:38 UTC, 747mmHg commented on bdse-app/src/main/java/ru/csc/bdse/app/v2/service/ServiceV2.java
> +        berkleyKeyValueApi.put("@" + nickName, byteKey);
Кажется, это не будет работать в случае, когда у разных пользователей (с разными именем/фамилией) одинаковые никнеймы

2018-03-19 19:32 UTC, sinesight commented on bdse-app/src/main/java/ru/csc/bdse/app/v2/service/ServiceV2.java
> +        berkleyKeyValueApi.put("@" + nickName, byteKey);
Хорошо, исправим. Мне показалось более логичным, что никнеймы тоже должны быть уникальными (как и комбинации фамилия + имя).

2018-03-20 20:27 UTC, istarion commented on README_TASK2.md
> +* Предполагается, что поле Фамилия не начинается с символа '@'.
Добавил проверку с возвратом 422 ошибки и сообщением.

2018-03-20 20:36 UTC, istarion commented on bdse-app/src/main/java/ru/csc/bdse/app/v1/service/ServiceV1.java
> +        return record.getSecondName() + record.getFirstName();
Добавил вставку символа ';' между словами. Правильнее всего было бы ещё добавить валидацию при вставке и написать тесты на такой кейс, но мы это пока оставим в бэклоге.

2018-03-20 22:41 UTC, sinesight commented on bdse-app/src/main/java/ru/csc/bdse/app/v2/service/ServiceV2.java
> +        berkleyKeyValueApi.put("@" + nickName, byteKey);
Fixed.

2018-03-20 22:41 UTC, sinesight commented on bdse-app/src/main/java/ru/csc/bdse/app/v1/service/ServiceV1.java
> +        return record.getSecondName() + record.getFirstName();
(исправили на '@' для единообразия)

2018-03-21 11:11 UTC, 747mmHg commented on bdse-app/src/main/java/ru/csc/bdse/app/v11/controller/BookControllerV11.java
> +    @RequestMapping(method = RequestMethod.POST)
Строго говоря это PUT, потому что повторный запрос с такими же параметрами не приведёт к созданию новой записи.

2018-03-21 11:11 UTC, 747mmHg approved these changes
👍

2018-03-25 08:27 UTC, merged