Replicated KeyValueApi
csc-bdse-group-42/csc-bdse pull request #4
Opened 2018-04-05 19:57 UTC by StepaMalkevich

2018-04-10 18:49 UTC, semkagtn requested changes

2018-04-10 18:49 UTC, semkagtn commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/InMemoryKeyValueApi.java
> +        return "OK";
Наверное, здесь хотелось написать всё-таки `"COMMIT"`.

2018-04-10 18:49 UTC, semkagtn commented on bdse-kvnode/src/main/java/ru/csc/bdse/resolver/Resolver.java
> +            Map<byte[], List<KeyValueRecord>> mapGroupByData = keyValueRecords.stream().
Так нельзя делать. Для типа `byte[]` не определены верным образом операции `equals` и `hashCode`.

2018-04-10 18:49 UTC, semkagtn commented on bdse-kvnode/src/main/java/ru/csc/bdse/resolver/Resolver.java
> +            if (countUniqueListSize == 1) {
Здесь, честно говоря, логика немного странная.
Во-первых, не очень понятно почему при `countUniqueListSize == 1` и при `countUniqueListSIze != 1` алгоритм различается. Во-вторых желателен детерминированный алгоритм, как следует из описания задачи. Этот алгоритм таковым сейчас не является.

2018-04-10 18:49 UTC, semkagtn commented on bdse-kvnode/src/main/java/ru/csc/bdse/resolver/ConflictResolver.java
> +    Optional<KeyValueRecord> resolve(Set<KeyValueRecord> keyValueRecords);
Кажется в описании задачи присутствует ошибка.
Нужно сменить сигнатуры методов на:
```java
Optional<KeyValueRecord> resolve(List<KeyValueRecord> keyValueRecords);
Set<String> resolveKeys(List<Set<String>> in);
```
Иначе рискуем нечестно посчитать результат, так как в `Set` одинаковые значения "схлопнутся".

2018-04-10 18:49 UTC, semkagtn commented on bdse-kvnode/src/main/java/ru/csc/bdse/resolver/Resolver.java
> +public class Resolver implements ConflictResolver {
Не хватает unit-тестов на `Resolver`, что требуется по заданию.

2018-04-10 18:51 UTC, semkagtn commented
Как я понял, задача до конца не доделана. Не хватает ещё интеграционных тестов, а также `INSTALL_TASK3.md` и `README_TASK3.md`.

2018-04-10 19:08 UTC, StepaMalkevich commented on bdse-kvnode/src/main/java/ru/csc/bdse/resolver/Resolver.java
> +            if (countUniqueListSize == 1) {
Здесь имелось в виду, что сначала берем из Set<KeyValueRecord> только те записи, у которых время == максимальному времени среди всех записей в этом множестве. Далее группируем записи по значению данных (это чтобы потом взять те данные, которые присутствуют максимальное число раз). Потом проверяется, что если все группы присутствуют одинаковое число раз (countUniqueListSize == 1), то детерминированным алгоритмом (выбирается тот, у которого длина максимальная <- вот тут, видимо, ошибка нужно не по максимальной длине выбирать, так как это недетерминированный выбор).

2018-04-10 19:08 UTC, semkagtn commented on bdse-kvnode/src/main/java/ru/csc/bdse/resolver/Resolver.java
> +            if (countUniqueListSize == 1) {
Можете подсмотреть реализацию у ребят: https://github.com/DB1L/csc-bdse/pull/3/files#diff-ef8f977fd6b96cceb454cc980cdcac3eR11

2018-04-11 09:38 UTC, semkagtn commented on bdse-kvnode/src/main/java/ru/csc/bdse/resolver/Resolver.java
> +            if (countUniqueListSize == 1) {
Если у нас есть три группы: в первой - 1 элемент, во второй - 2 элемента, в третьей - 2 элемента. Тогда `countUniqueListSize == 2`, следовательно попадаем во вторую ветку. По описанному алгоритму выберем либо элемент из второй группы, либо из третьей. Это тоже неоднозначность.

2018-04-16 12:26 UTC, semkagtn commented
Сейчас код не компилируется:
```
...
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.241 s
[INFO] Finished at: 2018-04-16T15:25:01+03:00
[INFO] Final Memory: 42M/338M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project bdse-integration-tests: Compilation failure: Compilation failure:
[ERROR] /Users/semkagtn/IdeaProjects/csc-bdse-forks/csc-bdse/bdse-integration-tests/src/test/java/ru/csc/bdse/kv/AbstractKeyValueApiTest.java:[31,44] incompatible types: java.util.Optional<ru.csc.bdse.model.KeyValueRecord> cannot be converted to java.util.Optional<byte[]>
...
```

Если исправите, готов поставить 4 за это задание (так как нету интеграционных тестов).

2018-04-16 20:35 UTC, istarion commented
@semkagtn , мне пришлось отключить некоторые тесты, т.к. из-за добавления tombstone записей сломалась некоторая логика в bdse-app и её тестах.

2018-04-16 20:47 UTC, semkagtn commented
@istarion Давайте исправим баги. Потому что без этого поставить 4 не могу.

2018-04-17 18:47 UTC, istarion commented
@semkagtn , починил все тесты.

2018-04-17 20:06 UTC, semkagtn approved these changes
Ок. Ставлю оценку 4, так как нету интеграционных тестов для этого задания.

2018-04-19 10:16 UTC, merged