CSC BDSE Task4
csc-bdse-group-42/csc-bdse pull request #5
Opened 2018-04-26 17:36 UTC by sinesight

2018-05-02 10:38 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/PartitionedKeyValueApi.java
> +        return "COMMIT";
А почему такое странное значение возвращаем?

2018-05-02 10:38 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/PartitionedKeyValueApi.java
> +        return null;
Мы ведь можем здесь инфу о кластере вывести?

2018-05-02 10:40 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/PartitionedKeyValueApiHttpClient.java
> +                nodes.get(i).put(key, value);
Не очень понятно, почему это задача клиента - реплицировать данные между узлами.

2018-05-02 10:42 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/kv/PartitionedKeyValueApiHttpClient.java
> +public class PartitionedKeyValueApiHttpClient {
Не понятно, какая роль у этого "клиента".
Написано,  что он `Partitioned`, а на самом деле он реплицирует данные при записи, а при чтении перебором пытается найти узел, на котором есть требуемый ключ.
Для реализации выбора узла как раз нужно использовать одну из стратегий партицирования.

2018-05-02 10:44 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/partitioning/PartitionCoordinator.java
> +            throw new IllegalStateException("Time error while recording");
А только ли Time error-ы тут могут быть?

2018-05-02 10:46 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/partitioning/PartitionCoordinator.java
> +                    NodeClient nodeClient = Feign.builder().decoder(new JacksonDecoder()).target(NodeClient.class, nodeUrl);
А не затратно на каждый вызов метода создавать `Feign`, а так же `JacksonDecoder`-ы?

2018-05-02 10:47 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/partitioning/PartitionCoordinator.java
> +            if (e.getMessage().startsWith("feign.FeignException: status 404")) {
Шаткая, конечно, проверочка :)

2018-05-02 10:48 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/partitioning/PartitionCoordinator.java
> +                keys = null;
А точно правильно `null` возвращать, а не бросать исключение?

2018-05-02 10:49 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/partitioning/PartitionCoordinator.java
> +                    return "COMMIT";
Коли протокол построен на строковых значениях, было бы хорошо вынести возможные значения в константы и переиспользовать их.

2018-05-02 10:51 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/partitioning/PartitionCoordinator.java
> +                    return "COMMIT";
Так же можно добавит вспомогательные функции `isSuccess(String result)`, куда запрятать `result.equals(SUCCESS)`. Клиентский код будет чуть более читабельным.

2018-05-02 10:52 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/partitioning/PartitionCoordinator.java
> +    private int timeout;
Почему не final?

2018-05-02 10:54 UTC, dormidon requested changes
В целом все хорошо, есть вопросы про `PartitionedKeyValueApiHttpClient` - его назначение и смысл, а так же реализацию соответствующего теста. Будете дополнять/исправлять/предоставлять информацию?

2018-05-07 11:16 UTC, dormidon commented
Коллеги, вы планируете дополнять?
Направление у вас правильное, но основное - тесты - не сделаны. Без этого оценка только "3".

2018-05-08 20:43 UTC, sinesight commented
Видимо, дополнить не успеваем. Извините.

2018-05-09 08:52 UTC, istarion commented
Я попробую сегодня доделать

2018-05-09 14:24 UTC, istarion commented
@dormidon , исправил основные проблемы. У меня не получилось сделать воспроизводимым ConsistentPartitionerTest т.к. у нас в качестве имени ноды используется URL, и он меняется при каждом запуске теста из-за нового маппинга порта.

2018-05-09 19:50 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/controller/PartitionedKeyValueApiController.java
> +public class PartitionedKeyValueApiController {
А почему не подошел контроллер от просто `KeyValueApi`?

2018-05-09 21:49 UTC, istarion commented on bdse-kvnode/src/main/java/ru/csc/bdse/controller/PartitionedKeyValueApiController.java
> +public class PartitionedKeyValueApiController {
Контроллер от KeyValueApi задуман как внутренний, и он использует BerkleyKeyValueApi. Получается, что у любой ноды есть партиционированный публичный API, и низкоуровневый приватный.

2018-05-10 08:23 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/controller/PartitionedKeyValueApiController.java
> +public class PartitionedKeyValueApiController {
Все равно не очень понятно, почему интерфейс партицированной реализации должен отличаться от интерфейса обычной реализации.
Ведь фича партицирования - это именно деталь реализации.

Ок. Большая часть тестов написана, но на отлично немного не дотянули. Ставим "хорошо".

2018-05-10 08:28 UTC, istarion commented on bdse-kvnode/src/main/java/ru/csc/bdse/controller/PartitionedKeyValueApiController.java
> +public class PartitionedKeyValueApiController {
Я просто не знаю как в спринге переиспользовать тот-же самый рест контроллер, но с внедрением других зависимостей и на другом эндпоинте. Принципиальных ограничений нет.

2018-05-10 08:30 UTC, dormidon commented on bdse-kvnode/src/main/java/ru/csc/bdse/controller/PartitionedKeyValueApiController.java
> +public class PartitionedKeyValueApiController {
Я видел, что где-то делают базовый класс со всей реализацией, потом только наследуются от него и добавляют нужные аннотации, необходимые для работы механизмов Спринга. Но даже это не выглядит элегантным решением :)

2018-05-10 12:58 UTC, merged